name: Deploy

on:
  push:
    branches:
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Log Node & OS versions
        run: |
          node -v
          cat /etc/os-release

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node 22.x
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MY_AWS_ACCESS_SECRET_ID }}
          aws-region: ${{ secrets.MY_AWS_DEFAULT_REGION }}

      - name: Install dependencies
        run: npm i

      - name: Build project
        run: npm run build

      - name: Deploy project
        run: |
          sam deploy \
            --stack-name wizard-excel-service \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --parameter-overrides \
            Bucket="${{ secrets.MY_AWS_S3_BUCKET }}" \
            --region '${{ secrets.MY_AWS_DEFAULT_REGION }}' \
            --resolve-s3
